#!/bin/sh

# Start the Simple X Hotkey Daemon
sxhkd &

# Hide the mouse cursor after 2 seconds of inactivity and with 10 pixels jitter
unclutter -idle 2 -jitter 10 -root -noevents &

# Set the keyboard repeat rate to 40 per second with a delay of 200 milliseconds
xset r rate 200 40 &

# Start the dwm status script
$HOME/dotfiles/scripts/dwmstatus.sh &

# Start the script to change keyboard layout
$HOME/code/scripts/utility/change-keyboard-layout.sh &

# Start the dynamic window manager (dwm)
exec dwm
